# TensorFlow 2 Keras vs. PyTorch

Differently from the AN2DL course the lectures will use Pytorch. Most of the code is extramly similar. The goal of this notebook is to provide a fast overview of the two frameworks and get an idea on how to write a model in Pytorch diffears from Kersa.

## 1. Setup & Environment

We start by importing the necessary libraries. In this lecture we use TensorFlow 2’s Keras and PyTorch.


In [ ]:
# TensorFlow 2 and tf.keras
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

# PyTorch
import torch
import torch.nn as nn
import torch.optim as optim
print("PyTorch version:", torch.__version__)

TensorFlow version: 2.18.0
PyTorch version: 2.5.1+cu124


## 2. Basic Tensor Operations: tf2 Keras vs. PyTorch

Both frameworks use tensors as their core data structure. In tf2 Keras (via TensorFlow) you often work with `tf.Tensor` objects (or NumPy arrays), while PyTorch uses `torch.Tensor`.

In [ ]:
# TensorFlow example: Creating and manipulating a tensor
a_tf = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
print("TensorFlow Tensor:")
print(a_tf)

# Basic arithmetic
b_tf = tf.ones_like(a_tf)
print("\nTensorFlow: a_tf + ones:")
print(a_tf + b_tf)

TensorFlow Tensor:
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

TensorFlow: a_tf + ones:
tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)


In [ ]:
# PyTorch example: Creating and manipulating a tensor
a_torch = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print("PyTorch Tensor:")
print(a_torch)

# Basic arithmetic
b_torch = torch.ones_like(a_torch)
print("\nPyTorch: a_torch + ones:")
print(a_torch + b_torch)

PyTorch Tensor:
tensor([[1., 2.],
        [3., 4.]])

PyTorch: a_torch + ones:
tensor([[2., 3.],
        [4., 5.]])


## 3. Model Definition

In this section, we will define a simple feed-forward network that maps an input of size 10 to an output of size 1. We’ll do this using both the Sequential API and model subclassing.

### 3.1 Using the Sequential API

In [ ]:
# tf2 Keras Sequential model
from tensorflow.keras import layers, Sequential

model_tf = Sequential([
    layers.Dense(50, activation='relu', input_shape=(10,)),
    layers.Dense(1)
])

model_tf.compile(optimizer='adam', loss='mse')
print("\nTensorFlow (tf2 Keras) Model Summary:")
model_tf.summary()


TensorFlow (tf2 Keras) Model Summary:


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 50)                  │             550 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 601 (2.35 KB)

 Trainable params: 601 (2.35 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# PyTorch Sequential model
model_torch = nn.Sequential(
    nn.Linear(10, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

print("\nPyTorch Model Structure:")
print(model_torch)


PyTorch Model Structure:
Sequential(
  (0): Linear(in_features=10, out_features=50, bias=True)
  (1): ReLU()
  (2): Linear(in_features=50, out_features=1, bias=True)
)


### 3.2 Using Model Subclassing / Custom Modules

Sometimes you need more flexibility than a Sequential model. Both frameworks support subclassing to create custom models.

In [ ]:
# tf2 Keras: Custom Model Subclassing
from tensorflow.keras import Model

class CustomModelTF(Model):
    def __init__(self):
        super(CustomModelTF, self).__init__()
        self.dense1 = layers.Dense(50, activation='relu')
        self.dense2 = layers.Dense(1)

    def call(self, inputs):
        x = self.dense1(inputs)
        return self.dense2(x)

# Instantiate and compile
custom_model_tf = CustomModelTF()
custom_model_tf.build(input_shape=(None, 10))
custom_model_tf.compile(optimizer='adam', loss='mse')
print("\nCustom tf2 Keras Model Summary:")
custom_model_tf.summary()


Custom tf2 Keras Model Summary:


/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py:393: UserWarning: `build()` was called on layer 'custom_model_tf_1', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(


Model: "custom_model_tf_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# PyTorch: Custom Model Subclassing using nn.Module

class CustomModelTorch(nn.Module):
    def __init__(self):
        super(CustomModelTorch, self).__init__()
        self.dense1 = nn.Linear(10, 50)
        self.relu = nn.ReLU()
        self.dense2 = nn.Linear(50, 1)

    def forward(self, x):
        x = self.relu(self.dense1(x))
        return self.dense2(x)

# Instantiate
custom_model_torch = CustomModelTorch()
print("\nCustom PyTorch Model Structure:")
print(custom_model_torch)


Custom PyTorch Model Structure:
CustomModelTorch(
  (dense1): Linear(in_features=10, out_features=50, bias=True)
  (relu): ReLU()
  (dense2): Linear(in_features=50, out_features=1, bias=True)
)


## 4. Training Loops: Built-in vs. Custom

A key difference between tf2 Keras and PyTorch is how training loops are managed. tf2 Keras provides a high-level `fit()` method, differently PyTorch usually requires you to write your own training loop

### 4.1 Training with tf2 Keras (Built-in)

In [ ]:
# Generate synthetic data for training
import numpy as np
np.random.seed(42)

X_train = np.random.randn(100, 10)
y_train = np.random.randn(100, 1)

# Train the tf2 Keras model using built-in fit()
print("\nTraining tf2 Keras Model...")
history = model_tf.fit(X_train, y_train, epochs=20, batch_size=16, verbose=1)


Training tf2 Keras Model...
Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 1.4450  
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.1793 
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9710 
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9005 
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0299 
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8127 
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8967 
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8308 
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7922 
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8160 
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8096 
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7166  
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8073 
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7971 
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6562 
Epo

### 4.2 Training with PyTorch (Custom Training Loop)

In [ ]:
# Convert the synthetic data to PyTorch tensors
X_train_torch = torch.tensor(X_train, dtype=torch.float32)
y_train_torch = torch.tensor(y_train, dtype=torch.float32)

# Define loss function and optimizer
loss_fn = nn.MSELoss()
optimizer = optim.Adam(model_torch.parameters(), lr=0.01)

print("\nTraining PyTorch Model with custom loop...")
epochs = 20
for epoch in range(epochs):
    optimizer.zero_grad()
    predictions = model_torch(X_train_torch)
    loss = loss_fn(predictions, y_train_torch)
    loss.backward()
    optimizer.step()

    if epoch % 5 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.4f}")


Training PyTorch Model with custom loop...
Epoch 0: Loss = 0.9148
Epoch 5: Loss = 0.7148
Epoch 10: Loss = 0.5939
Epoch 15: Loss = 0.4792


## 5. Data Pipelines: tf.data vs. DataLoader

Finally, you have to load data, both frameworks provide some function to easily handle training data. TensorFlow uses the `tf.data`  to build scalable input pipelines, while PyTorch uses the `DataLoader` class.


In [ ]:
# tf.data pipeline example
dataset_tf = tf.data.Dataset.from_tensor_slices((X_train, y_train))
dataset_tf = dataset_tf.shuffle(buffer_size=100).batch(16)

print("\nFirst batch from tf.data pipeline:")
for batch in dataset_tf.take(1):
    print(batch)


First batch from tf.data pipeline:
(<tf.Tensor: shape=(16, 10), dtype=float64, numpy=
array([[-0.24123606,  0.3520554 , -1.25153942,  1.4437646 , -0.08215118,
         1.11729583,  0.34272535,  0.45675322,  0.56976728,  0.44770856],
       [-0.92323325, -1.35168461, -0.97587325,  1.0536418 , -0.94939889,
         2.63238206,  0.4933179 ,  0.18483612, -0.85835778,  0.70030988],
       [-0.04946371,  0.67481949, -1.12272202,  0.38240975,  0.16645221,
         0.49245126,  0.28916864,  2.45530014, -0.63773998, -0.53099696],
       [ 2.06074792,  1.75534084, -0.24896415,  0.97157095,  0.64537595,
         1.36863156, -0.96492346,  0.68605146,  1.05842449, -1.75873949],
       [ 0.177701  , -1.33534436,  0.38019785,  0.61058575,  0.55979045,
         1.08078073,  0.83392215,  0.45918008, -0.07016571, -1.66096093],
       [ 0.07156624, -0.47765745,  0.47897983,  0.33366211,  1.03753994,
        -0.5100164 , -0.26987494, -0.97876372, -0.44429326,  0.37730049],
       [ 0.32408397, -0.3850822

In [ ]:
# PyTorch DataLoader example
from torch.utils.data import TensorDataset, DataLoader

dataset_torch = TensorDataset(X_train_torch, y_train_torch)
dataloader_torch = DataLoader(dataset_torch, batch_size=16, shuffle=True)

print("\nFirst batch from PyTorch DataLoader:")
for batch in dataloader_torch:
    print(batch)
    break


First batch from PyTorch DataLoader:
[tensor([[-0.9747,  0.7871,  1.1586, -0.8207,  0.9634,  0.4128,  0.8221,  1.8968,
         -0.2454, -0.7537],
        [ 1.9647,  0.0353, -0.6997,  0.2140, -0.1123, -0.2210,  0.6142,  0.7575,
         -0.5305, -0.5758],
        [-0.2177,  1.0988,  0.8254,  0.8135,  1.3055,  0.0210,  0.6820, -0.3103,
          0.3242, -0.1301],
        [-0.5737, -0.5469, -0.0328, -0.5434, -0.7128,  0.1064, -0.2550,  1.5040,
         -2.6510,  1.0915],
        [-0.6017,  1.8523, -0.0135, -1.0577,  0.8225, -1.2208,  0.2089, -1.9597,
         -1.3282,  0.1969],
        [-0.8397, -0.5994, -2.1239, -0.5258, -0.7591,  0.1504,  0.3418,  1.8762,
          0.9504, -0.5769],
        [ 0.2110, -0.0967, -0.5449,  0.3991, -0.0376,  1.1033,  0.1142,  0.1503,
         -0.3636, -0.0569],
        [ 2.3147, -1.8673,  0.6863, -1.6127, -0.4719,  1.0890,  0.0643, -1.0777,
         -0.7153,  0.6796],
        [ 1.8490,  1.1266, -0.2689, -1.1065,  2.5734,  0.0592,  0.0139, -0.0241,
        